# Uncomment this file to enable multilanguage site support

[en]
contentDir = "content/en"
languageName = "English"
languagedirection = "ltr"
title = "Yumechi"
weight = 1
[en.params.sidebar]
subtitle = "ã„ã„å¤¢ã‚’ğŸŒ™"

[zh]
contentDir = "content/zh"
languageName = "ä¸­æ–‡"
languagedirection = "ltr"
title = "Yumechi"
weight = 2
[zh.params.sidebar]
subtitle = "å¥½æ¢¦ğŸŒ™"

[ja]
contentDir = "content/ja"
languageName = "æ—¥æœ¬èª"
languagedirection = "ltr"
title = "Yumechi"
weight = 3
[ja.params.sidebar]
subtitle = "ã„ã„å¤¢ã‚’ğŸŒ™"