baseURL = "https://yumechi.jp/"
theme = "hugo-future-imperfect-slim"
author = "Yumechi"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disqusShortName = "yumechi-kuni"

[permalinks]
  blog = "/:sections/:year/:title/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    title = "Yumechi"
    weight = 1
    copyright = '''Â© Yumechi.'''
    staticDir = "static"
    staticDirs2 = "static_en"
    [languages.en.params]
        [languages.en.params.header]
          navbarTitle = "Yumechi"
          languageMenu = true
        [languages.en.params.intro]
        header = "Yumechi"
        paragraph = '''
        Hi! This is Yumechiâ€™s personal website.ã€€(ã¤Ï‰`*)ï¾ƒï¾
        <ul>
          <li>UT Austin 2019-2023<br /></li>
          <li>Computational Biology, Japanese Learner</li>
          <li>ğŸ³ï¸â€âš§ï¸ MTF (Â´ï¼›Ï‰ï¼›ï½€) Post-op</li>
          <li>B+ -> Platelet Donor <img class="inline" src="/img/trima/icon_pas.gif">60 units</li> 
          <li>Cybersecurity</li>
          <li>Golang Lover</li>
        </ul>
        '''
          [languages.en.params.intro.pic]
            src = "/img/trima/en/btn_vista_operator.gif"
            width = "50em"
            alt = "Yumechi"
        [languages.en.params.sidebar]
        about = '''
        Japanese version may be different in content to optimize suitability for readers. <br />
        All opinions are solely my own. <br />
        E-mail inquiries are welcome! <br /><br />
        This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.
        '''
        [languages.en.menu]
          [[languages.en.menu.main]]
            name = "BLOG"
            identifier = "Blog"
            pre = ""
            url = "/blog/"
            weight = 10
          [[languages.en.menu.main]]
            name = "RESOURCE"
            identifier = "Resource"
            pre = ""
            url = "/resource/"
            weight = 15
          [[languages.en.menu.main]]
            name = "UnitDC"
            identifier = "UnitDC"
            pre = ""
            url = "https://yumechi.jp/unitdc/"
            weight = 20
  
  [languages.ja]
    contentDir = "content/ja"
    languageName = "æ—¥æœ¬èª"
    title = "ã‚†ã‚ã¡ã®å›½"
    weight = 2
    copyright = '''Â©  Yumechi.'''
    staticDir = "static"
    staticDirs2 = "static_ja"
    [languages.ja.params]
      [languages.ja.params.header]
        navbarTitle = "ã‚†ã‚ã¡ã®å›½"
        languageMenu = true
      [languages.ja.params.intro]
        header = "ã‚†ã‚ã¡ã®å›½"
        paragraph = '''
        ã‚†ã‚‹ã¡ã®ï¼ˆåŠåˆ†ï¼‰åŒ¿åãƒ–ãƒ­ã‚°ã€€(ã¤Ï‰`*)ï¾ƒï¾
        <ul>
          <li>ãƒ†ã‚­ã‚µã‚¹å¤§å­¦ã‚ªãƒ¼ã‚¹ãƒ†ã‚£ãƒ³æ ¡ã€€<br /></li>
          <li>è¨ˆç®—ç”Ÿç‰©ç§‘å­¦ æ—¥æœ¬èª å‹‰å¼·ä¸­</li>
          <li>ğŸ³ï¸â€âš§ï¸ MTF (Â´ï¼›Ï‰ï¼›ï½€)ã€€æ‰‹è¡“ -> 2022/01</li>
          <li>B+ -> è¡€å°æ¿æˆåˆ†çŒ®è¡€ã€€<img class="inline" src="/img/trima/icon_pas.gif">60å˜ä½</li>
          <li>ã‚µã‚¤ãƒãƒ¼ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ãƒã‚¤ãƒˆä¸­</li>
          <li>Golang å¤§å¥½ã</li>
        </ul>
        '''
        [languages.ja.params.intro.pic]
            src = "/img/trima/ja/btn_vista_operator.gif"
            width = "50em"
            alt = "Yumechi"
      [languages.ja.params.sidebar]
        about = '''
        èª­è€…ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£ã‚’å¯¾å¿œã®ãŸã‚ã«ã€è‹±èªç‰ˆã¨ã®è¨˜äº‹ã®å†…å®¹ã¯é•ã„ãŒã‚ã‚Šã¾ã™ã€‚<br />
        ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã¯è‡ªåˆ†ã®è€ƒãˆã ã‘ã§ã™ã€‚ã€€<br />
        é›»å­ãƒ¡ãƒ¼ãƒ«ã§è³ªå•ã¯æ­“è¿ã—ã¾ã™ã€‚ã€€<br /><br />
        ã“ã®ä½œå“ã¯ <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">ã‚¯ãƒªã‚¨ã‚¤ãƒ†ã‚£ãƒ–ãƒ»ã‚³ãƒ¢ãƒ³ã‚º è¡¨ç¤º - éå–¶åˆ© - æ”¹å¤‰ç¦æ­¢ 4.0 å›½éš› ãƒ©ã‚¤ã‚»ãƒ³ã‚¹</a>ã®ä¸‹ã«æä¾›ã•ã‚Œã¦ã„ã¾ã™ã€‚
        '''
      [languages.ja.menu]
        [[languages.ja.menu.main]]
          name = "è¨˜äº‹"
          identifier = "Blog"
          pre = ""
          url = "/blog/"
          weight = 10
        [[languages.ja.menu.main]]
          name = "å…±æœ‰"
          identifier = "Resource"
          pre = ""
          url = "/resource/"
          weight = 15
        [[languages.ja.menu.main]]
          name = "UnitDC"
          identifier = "UnitDC"
          pre = ""
          url = "https://yumechi.jp/unitdc/"
          weight = 20
        
[social]
  github = "eternal-flame-AD"
  email = "inquiry@yumechi.jp"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [module.hugoVersion]
  extended              = true
  min                   = "0.62.0"


[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "blog"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "reddit", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "ã‚†ã‚ã¡ã®ãã«ï¼š ç”Ÿç‰©ç§‘å­¦ã€€ã‚µã‚¤ãƒãƒ¼ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ã€€ãƒˆãƒ©ãƒ³ã‚¹ã‚¸ã‚§ãƒ³ãƒ€ãƒ¼ | Yumechiã€€Blog: Biology Cybersecurity Transgender"
    author              = "Yumechi"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    dynamicTitles       = true
    searchMenu          = false
    shareMenu           = true

  [params.intro]
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false


#    [params.intro.pic]
#      src                 = "img/main/logo.jpg"
#      shape               = "circle"
#      width               = ""
#      alt                 = "Hugo Future Imperfect Slim"

  [params.sidebar]
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.utterances]
    enabled             = false
    repo                = ""
    issueTerm           = "pathname"
    issueNumber         = ""
    label               = ""
    theme               = "github-light"

  [params.staticman]
    enabled             = true
    api                 = "yumechi.jp/.netlify/functions/comment_submit?api="  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""